### ISSUE TITLE
Strange behavior with Graal?

### ISSUE THREAD

**Issue by plata** [flathub/org.freedesktop.Sdk.Extension.openjdk11#11]
*DISCLAIMER*: I'm not fully sure if the issue is really in this extension or on my side.

I'm using this extension for the Phoenicis flatpak and it was working. Right now, I get strange errors from Graal:
```
java.lang.AbstractMethodError: Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:178)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:425)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
```
Using exactly the same command to run the application outside of flatpak (with the same jar's), does not cause this error.

See: https://github.com/PhoenicisOrg/phoenicis/pull/2205

I have the impression that this is somehow related to module handling.

The only difference I see right now is that flatpak has OpenJDK 11.0.7 and outside 11.0.6. Not sure if that can cause issues.

**EDIT**: After downgrading to commit `c554d684bdfc4ab5f09a99b554c3c9b219770416e4af257c2715b2810df2b850` (which corresponds to 0550d6b48c7f600d70721f60dc909a5c75921fb2), the error is gone.

**Comment by mbooth101** [comment]
How can I reproduce your problem? What jar and what command? It's not obvious to me what's going on here. The stacktrace you pasted above does not even contain any classes from the JDK...

**Comment by plata** [comment]
To reproduce:
```
git clone https://github.com/PhoenicisOrg/phoenicis.git
cd phoenicis
mvn clean package
cd phoenicis-dist/src/flatpak/
flatpak-builder build-dir org.phoenicis.playonlinux.yml --force-clean --user --install
flatpak run org.phoenicis.playonlinux phoenicis-playonlinux
```

**Comment by plata** [comment]
Might be that the issue occurs also with https://flathub.org/apps/details/org.phoenicis.playonlinux. I didn't validate that. Are the flatpaks recompiled against new extensions automatically?

**Comment by mbooth101** [comment]
Thanks I'll check it out

>  Are the flatpaks recompiled against new extensions automatically?

No, it requires a maintainer to trigger a rebuild.

**Comment by plata** [comment]
If the issue does not appear on startup, go to the apps tab and wait until the list is populated.

**Comment by mbooth101** [comment]
I need more detail. When I follow your instructions I get this:

```
$ flatpak run org.phoenicis.playonlinux phoenicis-playonlinux
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules spring.jcl and commons.logging export package org.apache.commons.logging.impl to module jsch
```

I tried running on the host system, outside of Flatpak, with the same results:

```
$ unzip -q phoenicis-dist/target/phoenicis-flatpak.zip
$ cd phoenicis-flatpak/
$ /usr/lib/jvm/java-11-openjdk/bin/java -Dapplication.environment.wineRuntime=false --module-path $(pwd)/lib/ --add-modules=jdk.crypto.ec,java.base,javafx.base,javafx.web,javafx.media,javafx.graphics,javafx.controls,java.naming,java.sql,java.scripting,jdk.internal.vm.ci,jdk.inter
nal.vm.compiler,org.graalvm.truffle,jdk.jsobject,jdk.xml.dom -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -cp "$(pwd)/lib/*" --upgrade-module-path=$(pwd)/lib/compiler.jar org.phoenicis.javafx.JavaFXApplication
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules spring.jcl and commons.logging export package org.apache.commons.logging.impl to module org.apache.commons.compress
```

This is definitely an error in your application, nothing to do with Flatpak. I still have no idea how you produced the error in the original report.

**Comment by plata** [comment]
I'm sorry. I forgot that there is a pending PR.
Please try with
```
git clone https://github.com/plata/phoenicis.git
cd phoenicis
git checkout flatpak-app-integration
```

**Comment by mbooth101** [comment]
I see, well on your branch I see this error:

```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - org.phoenicis.scripts.exceptions.ScriptException: org.graalvm.polyglot.PolyglotException: java.lang.AbstractMethodError: Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.injectors.EngineInjector.throwException(EngineInjector.java:23)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.handleError(PolyglotScriptEngine.java:96)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:66)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:55)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.injectors.ScriptUtilitiesInjector.injectInto(ScriptUtilitiesInjector.java:13)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngineFactory.lambda$createEngine$0(PhoenicisScriptEngineFactory.java:38)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at phoenicis.scripts@5.0-SNAPSHOT/org.phoenicis.scripts.engine.PhoenicisScriptEngineFactory.createEngine(PhoenicisScriptEngineFactory.java:38)
        at phoenicis.engines@5.0-SNAPSHOT/org.phoenicis.engines.EngineSettingsManager.lambda$fetchAvailableEngineSettings$2(EngineSettingsManager.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.graalvm.polyglot.PolyglotException: java.lang.AbstractMethodError: Receiver class org.graalvm.compiler.hotspot.management.HotSpotGraalManagement does not define or inherit an implementation of the resolved method 'abstract void initialize(org.graalvm.compiler.hotspot.HotSpotGraalRuntime, org.graalvm.compiler.hotspot.GraalHotSpotVMConfig)' of interface org.graalvm.compiler.hotspot.HotSpotGraalManagementRegistration.
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:178)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:425)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.hotspot.HotSpotTruffleCompilerImpl.getCompiler(HotSpotTruffleCompilerImpl.java:138)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.compiler.hotspot.HotSpotTruffleCompilerImpl.create(HotSpotTruffleCompilerImpl.java:115)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.java.HotSpotTruffleRuntime.newTruffleCompiler(HotSpotTruffleRuntime.java:94)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime.initializeTruffleCompiler(AbstractHotSpotTruffleRuntime.java:238)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime.access$100(AbstractHotSpotTruffleRuntime.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime$1.execute(AbstractHotSpotTruffleRuntime.java:206)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$RequestImpl.call(BackgroundCompileQueue.java:195)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:238)
```

This is slightly different to your reported problem, which I still don't know how to produce. However, this looks like a bug in Graal: https://github.com/graalvm/graaljs/issues/271

Maybe you can try a version of Graal that contains the cited fix: https://github.com/oracle/graal/commit/a9e215d375076ca808232cac84bfb9845c3acf22

**Comment by plata** [comment]
The latest Graal releases (20.0.1 and 19.3.2, see https://github.com/graalvm/graalvm-ce-builds/releases) are not yet available in Maven.
I've tested with 19.3.1 and that doesn't show the error. Nevertheless it's somewhat surprising for me because https://github.com/graalvm/graaljs/issues/271 states that JDK 11 should not have been affected by this bug. So why does it occur in flatpak with JDK 11 but not outside of flatpak?

**Comment by plata** [comment]
The latest Graal releases (20.0.1 and 19.3.2, see https://github.com/graalvm/graalvm-ce-builds/releases) are not yet available in Maven.
I've tested with 19.3.1 and that doesn't show the error. Nevertheless it's somewhat surprising for me because https://github.com/graalvm/graaljs/issues/271 states that JDK 11 should not have been affected by this bug. So why does it occur in flatpak with JDK 11 but not outside of flatpak?

**Comment by mbooth101** [comment]
> The latest Graal releases (20.0.1 and 19.3.2, see https://github.com/graalvm/graalvm-ce-builds/releases) are not yet available in Maven.

May still be worth trying...

> I've tested with 19.3.1 and that doesn't show the error. Nevertheless it's somewhat surprising for me because [graalvm/graaljs#271](https://github.com/graalvm/graaljs/issues/271) states that JDK 11 should not have been affected by this bug. So why does it occur in flatpak with JDK 11 but not outside of flatpak?

Could be because something got back-ported to 11.0.7. Did you try on Java 11.0.7 outside of Flatpak?

**Comment by plata** [comment]
> May still be worth trying...

I will when it's available. Should not take too long.
> Did you try on Java 11.0.7 outside of Flatpak?

No, I only have 11.0.6 available.

**Comment by mbooth101** [comment]
> > May still be worth trying...
> 
> I will when it's available. Should not take too long.
> 
> > Did you try on Java 11.0.7 outside of Flatpak?
> 
> No, I only have 11.0.6 available.

Okay... Not sure what's stopping you trying either of these things, but if you are satisfied that the issue goes away when you change only the Graal version and all other things remain the same, then I am satisfied that the issue is in Graal and not in OpenJDK :-)

**Comment by plata** [comment]
I just don't want to fetch the packages manually, especially if the Maven package will probably be available in the next days ;).

**Comment by plata** [comment]
I've just tried with Java 11.0.7. Still the same issue.

**Comment by mbooth101** [comment]
> I've just tried with Java 11.0.7. Still the same issue.

Yes. I thought we agreed the problem is in graal...... You could trivially install the pre-releases of graal into your local maven repo and test this, but for some reason you haven't yet?

**Comment by plata** [comment]
> You could trivially install the pre-releases of graal into your local maven repo and test this, but for some reason you haven't yet?

I think that I misunderstood the graal releases I've linked above. The 20.0.1 and 19.3.2 pre-releases seem to be the LLVM Toolchain only.

**Comment by plata** [comment]
I cannot reproduce this anymore.
