### ISSUE TITLE
Could not generate ECDH keypair

### ISSUE THREAD

**Issue by mbooth101** [flathub/org.freedesktop.Sdk.Extension.openjdk11#2]
When accessing a site that is secured with a let's encrypt cert I see this error:

```
bash-4.4$ /app/jre11/bin/java -cp ~ SSLTest
Exception in thread "main" javax.net.ssl.SSLException: Could not generate ECDH keypair
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at SSLTest.main(SSLTest.java:13)
Caused by: java.lang.RuntimeException: Could not generate ECDH keypair
        at java.base/sun.security.ssl.ECDHKeyExchange$ECDHEPossession.<init>(ECDHKeyExchange.java:117)
        at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:575)
        at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:88)
        at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:263)
        at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:532)
        at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:228)
        at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:630)
        at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:515)
        at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:104)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:228)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
        ... 6 more
Caused by: java.security.NoSuchAlgorithmException: EC KeyPairGenerator not available
        at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:236)
        at java.base/sun.security.ssl.JsseJce.getKeyPairGenerator(JsseJce.java:237)
        at java.base/sun.security.ssl.ECDHKeyExchange$ECDHEPossession.<init>(ECDHKeyExchange.java:109)
        ... 16 more
```

**Comment by mbooth101** [comment]
To fix this, it is necessary to build OpenJDK against the system version of NSS that is provided by org.freedesktop.Sdk instead of building against the version of NSS bundled with the JDK.

**Comment by mbooth101** [comment]
I switched to using a source tarball that includes a bundled version of NSS. I hate to do this, because of course it won't receive security fixes that are applied to the freedesktop runtime, but it should at least make the JDK usable in the short term.

In the long term, I think OpenJDK probably wants to fix it's use of NSS since it requires some private headers and there resistance to exposing those in the freedesktop runtime (perhaps rightly so.)

But I don't have the time to fight battle right now -- I will keep PR #3 open as a reminder.

**Comment by mtecaitec** [comment]
We are  on OpenJDK 11.0.1. We have an application (servlet) running on tomcat and it tries to communicate with external service running on https. We have imported the certificate used by external service to key store. However we get the following SSL exception while the application tries to invoke the external service URL

**javax.net.ssl.SSLException: Could not generate ECDH** keypairjava.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:241)

we are relying on the default provider. Given below are the list of providers in our java.security file

#
# List of providers and their preference orders (see above):
#
security.provider.1=SUN
security.provider.2=SunRsaSign
security.provider.3=SunEC
security.provider.4=SunJSSE
security.provider.5=SunJCE
security.provider.6=SunJGSS
security.provider.7=SunSASL
security.provider.8=XMLDSig
security.provider.9=SunPCSC
security.provider.10=JdkLDAP
security.provider.11=JdkSASL
security.provider.12=SunMSCAPI
security.provider.13=SunPKCS11


We haven't configured any preferred providers for specific algorithms. See below

#jdk.security.provider.preferred=


We found that sunec.jar was missing with OpenJDK 11.0.1 which got shipped with earlier versions. However we tried using the sunec.jar from the earlier version and it didn't make any difference. 

Do we need to configure any more in java.security file? Do you think we shall need to revise the EC KeySize?

jdk.tls.legacyAlgorithms= \
        K_NULL, C_NULL, M_NULL, \
        DH_anon, ECDH_anon, \
        RC4_128, RC4_40, DES_CBC, DES40_CBC, \
        3DES_EDE_CBC

jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
    EC keySize < 224, 3DES_EDE_CBC

jdk.tls.keyLimits=AES/GCM/NoPadding KeyUpdate 2^37

jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224


Any help or directions would be greatly appreciated.

**Comment by mbooth101** [comment]
> We are on OpenJDK 11.0.1.

The current version of the OpenJDK11 extension in Flathub is 11.0.2 -- please pull the latest version from Flathub and rebuild your application to see if the problem is still there.

If you still experience the problem, then please open a new ticket and I will take a look

Thanks
